### ISSUE TITLE
Support for multiple (ordered) flows per data set

### ISSUE THREAD

**Issue by simanadler** [fybrik/fybrik#1231]
Users may indicate more than one flow for a dataset, and the order in which they should take place
Ex: read and write, write and copy

Also need to provide a way to indicate when there is a completion dependency
Ex: If copy and delete are indicated, copy has to complete before delete can occur.
Ex: If read and write are indicated there is no such hard dependency

**Comment by shlomitk1** [comment]
@simanadler @roytman The only use-case the multiple flows per one entry in Data[] array make sense is when the datasetID of the second operation is not known in advance and is a direct result of the first operation, for example: create(write) datasetX and copy datasetX to datasetY, or read datasetX. 
For all other use-cases, such as read & write, copy & delete - it is simpler to have multiple entries in Data[] with the same datasetID, with a possible dependency option. Otherwise, you need to provide semantics: copy + delete means copy datasetX to datasetY, delete datasetX when copy + read means copy datasetX to datasetY, read datasetY.

**Comment by simanadler** [comment]
On further discussion, it's not clear that we really want to provide this functionality.  A list is not sufficient to indicate the dependencies between the steps in the flow ... and something more comprehensive will be too complicated for the user.
