### ISSUE TITLE
Add notebook sample to show the case of writing new asset

### ISSUE THREAD

**Issue by revit13** [fybrik/fybrik#1459]
A notebook sample with write flow should be added to the quick start

**Comment by simanadler** [comment]
Potential scenarios:

@shlomitk1 suggested:
The scenario you probably want to demonstrate is:
a new asset has a sensitive field
Fybrik is deployed with storage in regions r1 and r2 (whatever their names are...)
A governance policy forbids to write sensitive data to regions r1 and r2

 I agree that @shlomitk’s scenario is one option except how do we know there is a sensitive field since the data hasn’t been written yet? I guess the user could provide metadata indicating that.

Another potential scenario is the user is requesting to write to a type of storage (ex: dropbox) not supported by the enterprise .  In that case the governance policy would relate to the connection received from the catalog.
1. User creates a catalog entry ahead of time that has a connection to dropbox
2. In FybrikApplication user indicates the catalog entry and that he wants to write to it
3. Governance policy says that if the connection is of type dropbox, then deny. (If we don’t know how to parse the connection to figure out it’s dropbox, take a shortcut for now and just put a tag on the catalog entry)
4. Fybrik should receive deny from the governance engine

**Comment by shlomitk1** [comment]
Another option: the user role does not allow updating the catalog (write operation).

**Comment by simanadler** [comment]
@shlomitk1 That is the equivalent of saying that the user is not allowed to write data.  While valid technically, I'm looking for a scenario that has more business relevance.  The one I suggested is perhaps more complex, but it's actually the story that was used when we were first introducing the idea of fybrik to stakeholders.

**Comment by simanadler** [comment]
Another potential scenario is:

1. User is updating an existing catalog entry

**Comment by simanadler** [comment]
Another potential scenario is:
1. There is an existing catalog entry, which is in geography B
2. User's workload is in geography A
3. User requests to write to the existing asset
4. Deny is received, due to a governance policy that says workloads in geography A cannot write to datasets in geography B
@shlomitk1 @eres Would this make sense?

**Comment by revit13** [comment]
duplication of #1238
