### ISSUE TITLE
Enable admin config policies to define an action

### ISSUE THREAD

**Issue by shlomitk1** [fybrik/fybrik#1500]
**Background**: Current syntax of admin config policies returns deployment decisions and restrictions on module/cluster/storage account selection. 

We'd like to enhance the decision by providing an action that the selected module will implement. For example,
for a `delete` capability if a dataset resides in a bucket owned by Fybrik (according to the dataset tags), the chosen module will also delete the bucket.
Another example: archive the data before deleting the catalog entry.

**Comment by simanadler** [comment]
@shlomitk1 I think this is a bigger issue than just changing admin config policies.  This is really a discussion about whether such actions (ex: deleting a bucket) should be implemented as modules.  Correct?  If so, I suggest opening an issue or discussion about the whole topic rather than this very specific issue.

**Comment by shlomitk1** [comment]
Closing, needs more discussion.
