### ISSUE TITLE
Use Helm Upgrade for installs as well

### ISSUE THREAD

**Issue by shlomitk1** [fybrik/fybrik#1559]
Need to check whether using Upgrade with install option improves performance.

**Comment by roytman** [comment]
the helm `upgrade --install` is checked in the `cmd/helm/upgrade.go` , the test is done by checking `if _, err := histClient.Run(args[0]); err == driver.ErrReleaseNotFound {`. If the check is true, helms runs the `Install` action, otherwise `Upgrade`. 
From performance point of view it is exactly what is doing in `blue mix_controller.go`. In addition, we don't have access to the methods in `cmd/helm`

**Comment by shlomitk1** [comment]
So, what is the conclusion regarding Install option in Upgrade params? Is it just for documentation as written in the comments?

**Comment by roytman** [comment]
No, it does allow to install a new chart during its upgrade.  However,  it is done in the `cmd/helm` package by a package available functions, WE cannot use it.
You can close the issue.

**Comment by simanadler** [comment]
> No, it does allow to install a new chart during its upgrade. However, it is done in the `cmd/helm` package by a package available functions, WE cannot use it. You can close the issue.

@roytman Why can't we use it?

**Comment by roytman** [comment]
when `helm` run as a CLI command, it is going first to the Cobra "commands" in the cmd/helm package. The [newUpgradeCmd](https://github.com/helm/helm/blob/657850e44b880cca43d0606ebf5a54eb75362c3f/cmd/helm/upgrade.go#L69) function  (put attention on its visibility) [checks](https://github.com/helm/helm/blob/657850e44b880cca43d0606ebf5a54eb75362c3f/cmd/helm/upgrade.go#L94) if the `install` flag is set, and if it is && the release is not deployed, instead of the Upgrade action, it creates and runs the Install action.
Actually we do the same, we check if the release is deployed and if not we Install it, otherwise we upgrade it. 
We don't use the commands from the `cmd/helm` package and use directly the actions.

The only one way to use the feature (and maybe others ) is to run helm operations as an external CLI command.

**Comment by simanadler** [comment]
OK.  Thanks for the explanation.  @roytman
