### ISSUE TITLE
Manager: No error returned in write flow when bucket not allocated

### ISSUE THREAD

**Issue by simanadler** [fybrik/fybrik#1600]
Flow: write, Policies: allow all write scenario
FybrikApplication requesting the creation of a new dataset
dlf deployed
arrow-flight module deployed
fybrikstorageaccount defined, but secret credentials are wrong

FybrikApplication status never becomes ready, but no error is returned in the status.
In the manager log it says "No bucket has been provisioned"

**Comment by shlomitk1** [comment]
No error is returned in the status because no error is reported in the Dataset resource status - it says Pending.
This mechanism of sending a request to allocate a bucket via Dataset, and polling to ensure it is ok before generating a plotter is not ideal. I suggest to use direct sdk to create a bucket, in which case the response will be quick, including the success/failure status.

**Comment by shlomitk1** [comment]
The latest master version sets application in the error state with a detailed message. From my test:
```
message: 'An error was received for asset new-data . If the error persists,
            please contact an operator.Error description: could not create a bucket
            write-nb-default4cfda91a7328ad3a2ae4: The request signature we calculated
            does not match the signature you provided. Check your AWS Secret Access
            Key and signing method. For more information, see REST Authentication
            and SOAP Authentication for details.'
```
