### ISSUE TITLE
Integration test failure when it runs on OpenShift

### ISSUE THREAD

**Issue by roytman** [fybrik/fybrik#1635]
The integration [test](https://github.com/fybrik/fybrik/blob/f0dc75ebe926e1466196f487770d5ac6cdca0f0e/manager/controllers/app/blueprint_controller_test.go#L62), fails when it runs on OpenShift

```
• [FAILED] [30.324 seconds]
[unit-test] Blueprint Controller Real Env
[unit-test] /workspace/source/mesh-for-data/manager/controllers/app/blueprint_controller_test.go:62
[unit-test]   Blueprint
[unit-test]   /workspace/source/mesh-for-data/manager/controllers/app/blueprint_controller_test.go:63
[unit-test]     [It] Test Blueprint Deploy to Correct Namespace
[unit-test]     /workspace/source/mesh-for-data/manager/controllers/app/blueprint_controller_test.go:85
[unit-test] 
[unit-test]   Begin Captured GinkgoWriter Output >>
[unit-test]     STEP: Expecting blueprint to be created 07/21/22 17:41:32.488
[unit-test]     STEP: Expecting Blueprint to eventually be ready 07/21/22 17:41:32.504
[unit-test]   << End Captured GinkgoWriter Output
[unit-test] 
[unit-test]   Timed out after 30.020s.
[unit-test]   Blueprint is not ready after timeout!
[unit-test]   Expected
[unit-test]       <bool>: false
[unit-test]   to be true
[unit-test]   In [It] at: /workspace/source/mesh-for-data/manager/controllers/app/blueprint_controller_test.go:52
```

**Comment by roytman** [comment]
There was no clear indication, why the test failed in the log file.

**Comment by shlomitk1** [comment]
The real issue is that a resource was incorrect, and no validation was applied. I don't think that we need to create a mockup environment and run integration tests on OpenShift.

**Comment by shlomitk1** [comment]
I have run integration tests on OpenShift - they pass.

**Comment by shlomitk1** [comment]
{"level":"trace","Controller":"Blueprint","app.fybrik.io/app-uuid":"1234","blueprint":"fybrik-system/blueprint-with-read","Action":"Create","time":"2022-07-28T11:55:28Z","caller":"/data/ws/the-mesh-for-data/manager/controllers/app/blueprint_controller.go:79","message":"Installing/Updating blueprint blueprint-with-read"}
{"level":"trace","Controller":"Blueprint","app.fybrik.io/app-uuid":"1234","blueprint":"fybrik-system/blueprint-with-read","time":"2022-07-28T11:55:28Z","caller":"/data/ws/the-mesh-for-data/manager/controllers/app/blueprint_controller.go:330","message":"Release name: notebook-default-notebook-read-module"}
{"level":"trace","Controller":"Blueprint","app.fybrik.io/app-uuid":"1234","blueprint":"fybrik-system/blueprint-with-read","Action":"Create","time":"2022-07-28T11:55:28Z","caller":"/data/ws/the-mesh-for-data/manager/controllers/app/blueprint_controller.go:184","message":"--- Chart Ref ---\n\nghcr.io/fybrik/fybrik-template:0.1.0\n\n"}
{"level":"trace","Controller":"Blueprint","app.fybrik.io/app-uuid":"1234","blueprint":"fybrik-system/blueprint-with-read","Action":"Create","time":"2022-07-28T11:55:28Z","caller":"/data/ws/the-mesh-for-data/manager/controllers/app/blueprint_controller.go:191","message":"--- Values.yaml ---\n\nassets:\n- args:\n  - connection:\n      name: s3\n      s3:\n        bucket: fybrik-test-bucket\n        endpoint: https://s3.eu-gb.cloud-object-storage.appdomain.cloud\n        object_key: small.kp.encrypted.parq\n    format: parquet\n    vault:\n      read:\n        address: http://vault.fybrik-system:8200\n        authPath: /v1/auth/kubernetes/login\n        role: module\n        secretPath: /v1/kubernetes-secrets/secret-name?namespace=default\n  assetID: xyz\n  capability: read\ncontext: {}\nlabels:\n  app.fybrik.io/app-name: notebook\n  app.fybrik.io/app-namespace: default\n  app.fybrik.io/blueprint-name: blueprint-with-read\n  app.fybrik.io/blueprint-namespace: fybrik-system\nselector:\n  matchLabels:\n    app: notebook\nuuid: \"1234\"\n\n\n"}
Warning: chart media type application/tar+gzip is deprecated
Pulled: ghcr.io/fybrik/fybrik-template:0.1.0
Digest: sha256:ecdc32f0a6f266bd87800339704e96aee7c33ea0ff92bb0e25013a34be3dea7a
{"level":"debug","Controller":"Blueprint","app.fybrik.io/app-uuid":"1234","blueprint":"fybrik-system/blueprint-with-read","time":"2022-07-28T11:55:29Z","caller":"/data/ws/pkg/mod/helm.sh/helm/v3@v3.8.2/pkg/action/history.go:56","message":"getting history for release notebook-default-notebook-read-module"}
{"level":"debug","Controller":"Blueprint","app.fybrik.io/app-uuid":"1234","blueprint":"fybrik-system/blueprint-with-read","time":"2022-07-28T11:55:29Z","caller":"/data/ws/pkg/mod/helm.sh/helm/v3@v3.8.2/pkg/action/upgrade.go:142","message":"preparing upgrade for notebook-default-notebook-read-module"}
I0728 11:55:30.880072       1 request.go:665] Waited for 1.173704103s due to client-side throttling, not priority and fairness, request: GET:https://172.21.0.1:443/apis/extensions/v1beta1?timeout=32s
{"level":"debug","Controller":"Blueprint","app.fybrik.io/app-uuid":"1234","blueprint":"fybrik-system/blueprint-with-read","time":"2022-07-28T11:55:31Z","caller":"/data/ws/pkg/mod/helm.sh/helm/v3@v3.8.2/pkg/action/upgrade.go:150","message":"performing update for notebook-default-notebook-read-module"}
{"level":"debug","Controller":"Blueprint","app.fybrik.io/app-uuid":"1234","blueprint":"fybrik-system/blueprint-with-read","time":"2022-07-28T11:55:31Z","caller":"/data/ws/pkg/mod/helm.sh/helm/v3@v3.8.2/pkg/action/upgrade.go:322","message":"creating upgraded release for notebook-default-notebook-read-module"}
{"level":"debug","Controller":"Blueprint","app.fybrik.io/app-uuid":"1234","blueprint":"fybrik-system/blueprint-with-read","time":"2022-07-28T11:55:31Z","caller":"/data/ws/pkg/mod/helm.sh/helm/v3@v3.8.2/pkg/kube/client.go:218","message":"checking 0 resources for changes"}
{"level":"debug","Controller":"Blueprint","app.fybrik.io/app-uuid":"1234","blueprint":"fybrik-system/blueprint-with-read","time":"2022-07-28T11:55:31Z","caller":"/data/ws/pkg/mod/helm.sh/helm/v3@v3.8.2/pkg/kube/wait.go:48","message":"beginning wait for 0 resources with timeout of 5m0s"}
{"level":"debug","Controller":"Blueprint","app.fybrik.io/app-uuid":"1234","blueprint":"fybrik-system/blueprint-with-read","time":"2022-07-28T11:55:31Z","caller":"/data/ws/pkg/mod/helm.sh/helm/v3@v3.8.2/pkg/action/upgrade.go:157","message":"updating status for upgraded release for notebook-default-notebook-read-module"}
{"level":"trace","Controller":"Blueprint","app.fybrik.io/app-uuid":"1234","blueprint":"fybrik-system/blueprint-with-read","Action":"Create","time":"2022-07-28T11:55:31Z","caller":"/data/ws/the-mesh-for-data/manager/controllers/app/blueprint_controller.go:239","message":"--- Release Status ---\n\ndeployed\n\n"}
{"level":"trace","Controller":"Blueprint","app.fybrik.io/app-uuid":"1234","blueprint":"fybrik-system/blueprint-with-read","Action":"Update","time":"2022-07-28T11:55:31Z","caller":"/data/ws/the-mesh-for-data/manager/controllers/app/blueprint_controller.go:87","message":"Updating status for desired generation 1"}
{"level":"debug","Controller":"Blueprint","app.fybrik.io/app-uuid":"1234","blueprint":"fybrik-system/blueprint-with-read","time":"2022-07-28T11:55:31Z","caller":"/data/ws/the-mesh-for-data/manager/controllers/app/blueprint_controller.go:92","message":"blueprint reconcile cycle completed."}
{"level":"trace","Controller":"Blueprint","app.fybrik.io/app-uuid":"1234","blueprint":"fybrik-system/blueprint-with-read","Action":"Create","time":"2022-07-28T11:55:31Z","caller":"/data/ws/the-mesh-for-data/manager/controllers/app/blueprint_controller.go:79","message":"Installing/Updating blueprint blueprint-with-read"}
{"level":"trace","Controller":"Blueprint","app.fybrik.io/app-uuid":"1234","blueprint":"fybrik-system/blueprint-with-read","time":"2022-07-28T11:55:31Z","caller":"/data/ws/the-mesh-for-data/manager/controllers/app/blueprint_controller.go:330","message":"Release name: notebook-default-notebook-read-module"}
{"level":"debug","Controller":"Blueprint","app.fybrik.io/app-uuid":"1234","blueprint":"fybrik-system/blueprint-with-read","time":"2022-07-28T11:55:31Z","caller":"/data/ws/the-mesh-for-data/manager/controllers/app/blueprint_controller.go:92","message":"blueprint reconcile cycle completed."}

**Comment by shlomitk1** [comment]
{"level":"trace","Controller":"Blueprint","app.fybrik.io/app-uuid":"1234","blueprint":"fybrik-system/blueprint-with-read","Action":"Create","time":"2022-07-28T12:01:36Z","caller":"/data/ws/the-mesh-for-data/manager/controllers/app/blueprint_controller.go:79","message":"Installing/Updating blueprint blueprint-with-read"}
{"level":"trace","Controller":"Blueprint","app.fybrik.io/app-uuid":"1234","blueprint":"fybrik-system/blueprint-with-read","time":"2022-07-28T12:01:36Z","caller":"/data/ws/the-mesh-for-data/manager/controllers/app/blueprint_controller.go:330","message":"Release name: notebook-default-notebook-read-module"}
{"level":"trace","Controller":"Blueprint","app.fybrik.io/app-uuid":"1234","blueprint":"fybrik-system/blueprint-with-read","Action":"Create","time":"2022-07-28T12:01:36Z","caller":"/data/ws/the-mesh-for-data/manager/controllers/app/blueprint_controller.go:184","message":"--- Chart Ref ---\n\nghcr.io/fybrik/fybrik-template:0.1.0\n\n"}
{"level":"trace","Controller":"Blueprint","app.fybrik.io/app-uuid":"1234","blueprint":"fybrik-system/blueprint-with-read","Action":"Create","time":"2022-07-28T12:01:36Z","caller":"/data/ws/the-mesh-for-data/manager/controllers/app/blueprint_controller.go:191","message":"--- Values.yaml ---\n\nassets:\n- args:\n  - connection:\n      name: s3\n      s3:\n        bucket: fybrik-test-bucket\n        endpoint: https://s3.eu-gb.cloud-object-storage.appdomain.cloud\n        object_key: small.kp.encrypted.parq\n    format: parquet\n    vault:\n      read:\n        address: http://vault.fybrik-system:8200\n        authPath: /v1/auth/kubernetes/login\n        role: module\n        secretPath: /v1/kubernetes-secrets/secret-name?namespace=default\n  assetID: xyz\n  capability: read\ncontext: {}\nlabels:\n  app.fybrik.io/app-name: notebook\n  app.fybrik.io/app-namespace: default\n  app.fybrik.io/blueprint-name: blueprint-with-read\n  app.fybrik.io/blueprint-namespace: fybrik-system\nselector:\n  matchLabels:\n    app: notebook\nuuid: \"1234\"\n\n\n"}
Warning: chart media type application/tar+gzip is deprecated
Pulled: ghcr.io/fybrik/fybrik-template:0.1.0
Digest: sha256:ecdc32f0a6f266bd87800339704e96aee7c33ea0ff92bb0e25013a34be3dea7a
{"level":"debug","Controller":"Blueprint","app.fybrik.io/app-uuid":"1234","blueprint":"fybrik-system/blueprint-with-read","time":"2022-07-28T12:01:37Z","caller":"/data/ws/pkg/mod/helm.sh/helm/v3@v3.8.2/pkg/action/history.go:56","message":"getting history for release notebook-default-notebook-read-module"}
{"level":"debug","Controller":"Blueprint","app.fybrik.io/app-uuid":"1234","blueprint":"fybrik-system/blueprint-with-read","time":"2022-07-28T12:01:37Z","caller":"/data/ws/pkg/mod/helm.sh/helm/v3@v3.8.2/pkg/action/upgrade.go:142","message":"preparing upgrade for notebook-default-notebook-read-module"}
I0728 12:01:38.735598       1 request.go:665] Waited for 1.171372098s due to client-side throttling, not priority and fairness, request: GET:https://172.21.0.1:443/apis/iis.cpd.ibm.com/v1alpha1?timeout=32s
{"level":"debug","Controller":"Blueprint","app.fybrik.io/app-uuid":"1234","blueprint":"fybrik-system/blueprint-with-read","time":"2022-07-28T12:01:39Z","caller":"/data/ws/pkg/mod/helm.sh/helm/v3@v3.8.2/pkg/action/upgrade.go:150","message":"performing update for notebook-default-notebook-read-module"}
{"level":"debug","Controller":"Blueprint","app.fybrik.io/app-uuid":"1234","blueprint":"fybrik-system/blueprint-with-read","time":"2022-07-28T12:01:39Z","caller":"/data/ws/pkg/mod/helm.sh/helm/v3@v3.8.2/pkg/action/upgrade.go:322","message":"creating upgraded release for notebook-default-notebook-read-module"}
{"level":"debug","Controller":"Blueprint","app.fybrik.io/app-uuid":"1234","blueprint":"fybrik-system/blueprint-with-read","time":"2022-07-28T12:01:39Z","caller":"/data/ws/pkg/mod/helm.sh/helm/v3@v3.8.2/pkg/kube/client.go:218","message":"checking 0 resources for changes"}
{"level":"debug","Controller":"Blueprint","app.fybrik.io/app-uuid":"1234","blueprint":"fybrik-system/blueprint-with-read","time":"2022-07-28T12:01:39Z","caller":"/data/ws/pkg/mod/helm.sh/helm/v3@v3.8.2/pkg/kube/wait.go:48","message":"beginning wait for 0 resources with timeout of 5m0s"}
{"level":"debug","Controller":"Blueprint","app.fybrik.io/app-uuid":"1234","blueprint":"fybrik-system/blueprint-with-read","time":"2022-07-28T12:01:39Z","caller":"/data/ws/pkg/mod/helm.sh/helm/v3@v3.8.2/pkg/action/upgrade.go:157","message":"updating status for upgraded release for notebook-default-notebook-read-module"}
{"level":"trace","Controller":"Blueprint","app.fybrik.io/app-uuid":"1234","blueprint":"fybrik-system/blueprint-with-read","Action":"Create","time":"2022-07-28T12:01:39Z","caller":"/data/ws/the-mesh-for-data/manager/controllers/app/blueprint_controller.go:239","message":"--- Release Status ---\n\ndeployed\n\n"}
{"level":"trace","Controller":"Blueprint","app.fybrik.io/app-uuid":"1234","blueprint":"fybrik-system/blueprint-with-read","Action":"Update","time":"2022-07-28T12:01:39Z","caller":"/data/ws/the-mesh-for-data/manager/controllers/app/blueprint_controller.go:87","message":"Updating status for desired generation 1"}
{"level":"debug","Controller":"Blueprint","app.fybrik.io/app-uuid":"1234","blueprint":"fybrik-system/blueprint-with-read","time":"2022-07-28T12:01:39Z","caller":"/data/ws/the-mesh-for-data/manager/controllers/app/blueprint_controller.go:92","message":"blueprint reconcile cycle completed."}
{"level":"trace","Controller":"Blueprint","app.fybrik.io/app-uuid":"1234","blueprint":"fybrik-system/blueprint-with-read","Action":"Create","time":"2022-07-28T12:01:39Z","caller":"/data/ws/the-mesh-for-data/manager/controllers/app/blueprint_controller.go:79","message":"Installing/Updating blueprint blueprint-with-read"}
{"level":"trace","Controller":"Blueprint","app.fybrik.io/app-uuid":"1234","blueprint":"fybrik-system/blueprint-with-read","time":"2022-07-28T12:01:39Z","caller":"/data/ws/the-mesh-for-data/manager/controllers/app/blueprint_controller.go:330","message":"Release name: notebook-default-notebook-read-module"}
{"level":"debug","Controller":"Blueprint","app.fybrik.io/app-uuid":"1234","blueprint":"fybrik-system/blueprint-with-read","time":"2022-07-28T12:01:39Z","caller":"/data/ws/the-mesh-for-data/manager/controllers/app/blueprint_controller.go:92","message":"blueprint reconcile cycle completed.

**Comment by shlomitk1** [comment]
I don't see "Pulled: ghcr.io/fybrik/fybrik-template:0.1.0" in the original log. Values are incorrect as expected (caused by the wrong spec).

**Comment by shlomitk1** [comment]
@roytman I think I have found the problem. Look at these lines of Helmer.Pull implementation:
```
// Pull helm chart from repo
func (r *Impl) Pull(cfg *action.Configuration, ref, destination string) error {
	if r.localChartsMountPath != "" {
		var err error
		// if chart mounted in container, no need to pull
		if _, err = os.Stat(r.localChartsMountPath + chartsDir + ref); err == nil {
			return nil
		}
		return err
	}
	chartRef, err := parseReference(ref)
        ...
```

If manager is configured with local charts BUT the requested chart is not located there, the code will return an error.
I think `return err` is not needed, the code should move on to pulling a chart from the registry.

**Comment by roytman** [comment]
@shlomitk1 , I think you're right, THANKS for checking
