### ISSUE TITLE
Send a PR to operate-first/apps on each release automatically

### ISSUE THREAD

**Issue by eletonia** [fybrik/fybrik#523]
Dependent on #600 
This issue lists initial steps to get to a point where we can automatically send a PR to https://github.com/operate-first/apps so the latest Fybrik resources will be deployed to the Operate First cluster. @roee88 @ronenkat 
- [x] Add Makefile with the commands to generate the initial YAML and to run the `filterClusterScoped` script
- [x] Add `requirements.txt` for the python dependencies
- [x] Add `fybrik-system` or whatever we need to add below the type folders. For example `clusterrolebindings/fybrik-system/...`
- [x] Generate `kustomization.yaml` files in the python script
- [ ] Add a GitHub workflow go automate the process upto raising a PR

**Comment by roee88** [comment]
An example workflow that does something similar is https://github.com/IBM/the-mesh-for-data/blob/master/.github/workflows/chart-publish.yaml. 

The changes from it would be:
- instead of the charts repo checkout the operate-first/apps repo
- replace the run commands with the make commands you added and then copy the results info the right folder within the cloned apps dir
- don't use tibdex/github-app-token@v1 but rather use the Fork method of peter-evans/create-pull-request@v3 as described in https://github.com/peter-evans/create-pull-request/blob/master/docs/concepts-guidelines.md#push-pull-request-branches-to-a-fork

I suggest to try this on your own test repositories the mimick ibm/the-mesh-for-data and operate-first/apps.

**Comment by roee88** [comment]
As described in https://github.com/fybrik/fybrik/pull/816#issuecomment-988710351. Still missing:

- [ ] Avoid having copies of resources in https://github.com/fybrik/fybrik/tree/master/samples/operate-first
- [ ] Submit PR to the upstream apps repo, not to our fork. The use of the fork is intended for a place for creating a branch to submit the PR from. See https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#push-pull-request-branches-to-a-fork and the push-to-fork option.
- [ ] Unless we can completely remove `samples/operate-first` we should at least move it to somewhere else because it's not a sample.

**Comment by eletonia** [comment]
@roytman Where should we move [samples/operate-first](https://github.com/fybrik/fybrik/tree/master/samples/operate-first) to in our repository? Also where should documentation for Operate First deployment go?

**Comment by roytman** [comment]
Hi @eletonia , please put the `operate-first` files under the `integration/operate-first` dir in our repository. 
Can you create the operate-first.md file in the `intergartion` directory with the installation instructions.
