### ISSUE TITLE
Demonstrate how to make changes to taxonomy in runtime

### ISSUE THREAD

**Issue by ronenkat** [fybrik/fybrik#779]
Demonstrate how Fybrik taxonomy that reside in /tmp/taxonomy/taxonomy.json to be updated during run-time.

Tasks
- [ ] Write an overview describing the role of the taxonomy in the fybrik architecture and the default taxonomy provided in https://fybrik.io/dev/concepts/taxonomy
- [ ] Describe which actors/systems should update the different parts of the taxonomy in https://fybrik.io/dev/concepts/taxonomy  
- [ ] Assemble a sample git repo that will contain a sample taxonomy to be used in the documentation.
- [ ] Expand [custom taxonomy document](https://fybrik.io/dev/tasks/custom-taxonomy/) with how to compile and deploy the new taxonomy for a running deployment.(and change the title of the page to taxonomy)
- [ ] Document how to add a new element to the taxonomy. For example, new interface, new policy action, etc.

**Comment by simanadler** [comment]
@ronenkat Different taxonomies have different owners as is described in https://docs.google.com/document/d/1sfdcNI6PTIYWsSIznpNqJNQCdVaVFchYB2vljzUrlew/edit?usp=sharing.  Thus, the mechanisms for update and the actors who do those updates would be different.  

Some taxonomies would need to be updated via a connector. Example: If there is a new purpose used in policies, I would expect that the policy manager connector would have a mechanism to update purpose in the taxonomy.  If the geographies are managed by the data catalog, then it's connector would update them in the taxonomy.    Our connectors need to provide mechanisms for doing this.  These I believe have been yet to be defined/designed, and thus I suggest adding the relevant tasks.

On the other hand, modules are something managed by Fybrik.  It's the IT admin who deploys them, and who determines the capabilities available to the control plane for creating data planes.  Thus, a mechanism via which the admin can add these capabilities needs to be provided.  This mechanism also needs to be defined.

Technically, I would suggest the initial focus be on the modules.  I would specifically add tasks for new modules that provides (a) a new capability (b) new format and/or protocol (c) new transform action.

**Comment by simanadler** [comment]
@Mohammad-nassar10 Some ideas for a taxonomy example page.

Example 1: Add new intent

Using the quick start demo...
0. Submit a fybrikapplication.yaml that has intent=marketing.  This should fail validation and no FybrikApplication CRD will be created, because no marketing in taxonomy
1. Governance Officer writes a new policy (in OPA) - If intent is marketing and data is tagged as PII, then redact
2. Governance Officer adds a new intent value = marketing in application taxonomy
3. Redeploy fybrik helm charts with taxonomy
4. Submit a fybrikapplication.yaml that has intent=marketing.  Now it should pass validation and only the data that isn't personal should be returned 

Example 2: Add new transform
1. Write a new redact capability in the [arrow flight server](https://github.com/fybrik/arrow-flight-module/blob/master/afm/pep/actions.py) and call it redactY - _just copy and paste the current redact and change the redact value from XXXXX to YYYYY_
2. Add redactyAction to the actions in the [arrow flight module yaml](https://github.com/fybrik/arrow-flight-module/blob/master/module.yaml)
3. Write an OPA policy that says - If read and data is PII then **redactyAction** - i.e. new type of redact
4. Redeploy the arrow flight module yaml
5. Redeploy fybrik helm charts with taxonomy
6. Run the quickstart notebook scenario.  Redacted data should show YYYYY

@roee88 @Mohammad-nassar10 Do these example scenarios make sense to you?

**Comment by roee88** [comment]
Keep in mind that the default allows all values. You probably want to start with "deploy with example taxonomy" (we have one in samples) and then from there move to your scenarios.

**Comment by simanadler** [comment]
As we discussed @Mohammad-nassar10, let's simplify the examples to focus only on the taxonomy specific tasks.

1. Submit a fybrikapplication.yaml that has intent=marketing. This should fail validation and no FybrikApplication CRD will be created, because no marketing in taxonomy
2. Add a new intent value = marketing in application taxonomy
3. Redeploy fybrik helm charts with taxonomy
4. Submit a fybrikapplication.yaml that has intent=marketing. Now it should pass validation and only the data that isn't personal should be returned

Example 2: Add new transform
1. Deploy a fybrikmodule yaml that has a redactyAction in its list of actions.  This should fail.  If webhooks are deployed, then an error will be returned.  If not, an error will appear in the fybrikmodule.status
2. Add redactyAction to the module taxonomy as a new action
3. Redeploy fybrik helm charts with taxonomy
4. Deploy the fybrikmodule yaml from step #1.  It should succeed now
