### ISSUE TITLE
Move data movement operator to separate repo

### ISSUE THREAD

**Issue by simanadler** [fybrik/fybrik#857]
As per discussion #811 we want to move the data movement operator and the associated modules out of the main fybrik repo.

**Comment by froesef** [comment]
When extracting the motion controller should we keep the directory structure and deployment strategy as it is right now? Thus deployment using a helm chart etc? Or should we move closer to the standard kubebuilder example deploying with kubectl and kustomize? 

I propose to keep it as is so that the development is consistent within the organization and also keep the crd groups and names the same. 

Proposal for new repository name:  `data-movement-operator`.
@simanadler @roee88 if you're ok with the name I'll create the repository and start moving the code.

**Comment by simanadler** [comment]
Me too

**Comment by froesef** [comment]
The motion parts were moved out and removed from this repo in https://github.com/fybrik/fybrik/pull/924.
